CREATE TABLE EstadoServicio(Id INT AUTO_INCREMENT,
IdLinea TINYINT NOT NULL,
IdEstado TINYINT NOT NULL, 
IdTipoDia TINYINT NOT NULL,
HoraDesde TIME NOT NULL, 
HoraHasta TIME, 
Fecha DATE NOT NULL,
Descripcion VARCHAR(255), PRIMARY KEY (Id), 
FOREIGN KEY (IdLinea) REFERENCES Linea(Id), 
FOREIGN KEY (IdEstado) REFERENCES Estado(Id),
FOREIGN KEY (IdTipoDia) REFERENCES TipoDia(Id))
 