CREATE TABLE EstadoServicio(Id INT AUTO_INCREMENT,
IdLinea TINYINT NOT NULL,
IdEstado TINYINT NOT NULL, 
HoraDesde TIME NOT NULL, 
HoraHasta TIME, 
IdFecha INT NOT NULL,
Descripcion VARCHAR(255), PRIMARY KEY (Id), 
FOREIGN KEY (IdLinea) REFERENCES Linea(Id), 
FOREIGN KEY (IdEstado) REFERENCES Estado(Id),
FOREIGN KEY (IdFecha) REFERENCES FechaEstadoServicio(Id))
 