CREATE TABLE EstadoServicio(Id INT AUTO_INCREMENT,
IdLinea TINYINT NOT NULL,
IdEstado TINYINT NOT NULL, 
FechaDesde DATETIME NOT NULL, 
FechaHasta DATETIME, 
Descripcion VARCHAR(255), PRIMARY KEY (Id), FOREIGN KEY (IdLinea) REFERENCES Linea(Id), FOREIGN KEY (IdEstado) REFERENCES Estado(Id))